global_transactions:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schema_directory: 'target'
      schemas_and_paths:
        main: 'target/global_transactions.db'